// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsxxkcrzgqhytfcnugmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzeHhrY3J6Z3FoeXRmY251Z21iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTYxNDIsImV4cCI6MjA3MDE3MjE0Mn0.ct9S8d7_cS8HCPlu9nm-v_MVsZHplUVQ4wgihNtgxvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});